name: flagel_demography_cnn
channels:
  - conda-forge
dependencies:
  - python=2.7.*
  - pip
  - scipy
  - numpy
  - matplotlib
  - ipykernel
  - scikit-learn
  - tensorflow==1.1.0
  - pip:
    - keras==2.0.6
    - h5py